// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: proto/contract.proto

package orders

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrdersAPIClient is the client API for OrdersAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrdersAPIClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
}

type ordersAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewOrdersAPIClient(cc grpc.ClientConnInterface) OrdersAPIClient {
	return &ordersAPIClient{cc}
}

func (c *ordersAPIClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/server.OrdersAPI/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrdersAPIServer is the server API for OrdersAPI service.
// All implementations must embed UnimplementedOrdersAPIServer
// for forward compatibility
type OrdersAPIServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	mustEmbedUnimplementedOrdersAPIServer()
}

// UnimplementedOrdersAPIServer must be embedded to have forward compatible implementations.
type UnimplementedOrdersAPIServer struct {
}

func (UnimplementedOrdersAPIServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrdersAPIServer) mustEmbedUnimplementedOrdersAPIServer() {}

// UnsafeOrdersAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrdersAPIServer will
// result in compilation errors.
type UnsafeOrdersAPIServer interface {
	mustEmbedUnimplementedOrdersAPIServer()
}

func RegisterOrdersAPIServer(s grpc.ServiceRegistrar, srv OrdersAPIServer) {
	s.RegisterService(&OrdersAPI_ServiceDesc, srv)
}

func _OrdersAPI_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersAPIServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.OrdersAPI/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersAPIServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrdersAPI_ServiceDesc is the grpc.ServiceDesc for OrdersAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrdersAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.OrdersAPI",
	HandlerType: (*OrdersAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrdersAPI_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/contract.proto",
}
